# version: go install github.com/vektra/mockery/v3@v3.5.4
dir: mocks/{{ replaceAll "internal" "internal_" .InterfaceDirRelative }}
structname: '{{.InterfaceName}}'
pkgname: "{{.SrcPackageName}}"
filename: "{{.InterfaceName}}.go"
template: testify
template-data:
  unroll-variadic: true
packages:
  sigoleng/internal/service:
    interfaces:
      AllServices: {}
